### ISSUE TITLE
Can data binding init from Prism OnNavigatingTo or OnNavigatedTo event? 

### ISSUE THREAD

**Issue by wuhuangjia** [SuavePirate/DynamicStackLayout#1]
Hello, first thanks for your control, and when we use this control with data binding, we have to initial the ItemsSource from viewmodel's Constructor, can we init from **Prism's** OnNavigatingTo or OnNavigatedTo event? 

thanks for your response

**Comment by SuavePirate** [comment]
The collection will update if you notify property change on your collection, it just doesn't have events setup for an `ObservableCollection.CollectionChanged`. So if you instantiate a new `List` or `ObservableCollection` in your navigation methods, it should work. I do this currently in my own apps with this control.

**Comment by wuhuangjia** [comment]
Oh~~yeah, this is my fault, it is worked, thanks
